version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_USER: amir
      MYSQL_PASSWORD: amir55
      MYSQL_ROOT_PASSWORD: amir55619255
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: stationSki
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: amir
      SPRING_DATASOURCE_PASSWORD: amir55
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true  # Optional, add if you want to show SQL in logs
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect  # Optional, specify dialect
    networks:
      - app_network
    volumes:
      - app_data:/path/to/your/app/data  # Replace with the path inside the container where data should be stored

volumes:
  mysql_data:
  app_data:  # Volume for the Spring Boot application, if needed

networks:
  app_network:
